[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons,/usr/lib/python3/dist-packages/addons
admin_passwd = ${ODOO_MASTER_PASSWORD}
db_host = db
db_port = 5432
db_user = ${POSTGRES_USER}
db_password = ${POSTGRES_PASSWORD}
db_name = sistema_comercial_faculdade
dbfilter = ^sistema_comercial_faculdade$
list_db = False
proxy_mode = True
without_demo = True
workers = 0
max_cron_threads = 1
log_level = info
